# Generated by Django 3.1.13 on 2021-09-30 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0004_settings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Settings', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='settings',
            name='countries',
            field=models.ManyToManyField(blank=True, null=True, related_name='settings_list', to='newsfeed.Country'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, related_name='settings_list', to='newsfeed.Keyword'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='sources',
            field=models.ManyToManyField(blank=True, null=True, related_name='settings_list', to='newsfeed.Source'),
        ),
    ]
