# Generated by Django 3.1.13 on 2021-09-30 16:08

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('newsfeed', '0004_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='keywords',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of keywords', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Keywords'),
        ),
    ]
