# Generated by Django 3.1.13 on 2021-09-30 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0007_auto_20210930_2244'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
