# Generated by Django 3.1.13 on 2021-09-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0008_delete_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.TextField(),
        ),
    ]
