# Generated by Django 3.1.13 on 2021-09-30 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0009_auto_20210930_2301'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
