# Generated by Django 3.1.13 on 2021-09-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0010_auto_20210930_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='thumbnail',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
