# Generated by Django 3.1.13 on 2021-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0011_auto_20210930_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline',
            field=models.TextField(blank=True, null=True),
        ),
    ]
