# Generated by Django 3.1.13 on 2021-09-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0013_auto_20210930_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
