# Generated by Django 3.1.13 on 2021-10-01 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsfeed', '0015_auto_20211001_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='code',
            field=models.CharField(max_length=2, unique=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
